import assert from 'node:assert/strict'
import { after, before, test } from 'node:test'
import { BASE, api, completeLease, launch, newAccount, shot, signedInContext, watch } from '../lib.mjs'

/** Mettre en location : annonce reprise du bail et de la fiche, réglages gardés. */
let browser
before(async () => (browser = await launch()))
after(() => browser?.close())

test('annonce : montants repris du bail, mentions obligatoires, saisie gardée', async () => {
  const { token } = await newAccount()
  const { propertyId } = await completeLease(token)
  const first = await api(`/properties/${propertyId}/ad`, { token })
  assert.equal(first.settings.rentCents, 51000)
  assert.equal(first.settings.depositCents, 102000)
  assert.match(first.ad.text, /560 € par mois charges comprises/)
  const ctx = await signedInContext(browser, token)
  const page = await ctx.newPage()
  const errors = []
  watch(page, errors)
  await page.goto(`${BASE}/espace/logements/${propertyId}`)
  await page.getByRole('link', { name: 'Rédiger l’annonce' }).click()
  await page.getByText('Mentions obligatoires', { exact: true }).waitFor()
  await page.getByLabel('Description').fill('Studio lumineux à deux pas de la plage.')
  await page.getByText('Enregistré automatiquement').waitFor()
  await page.getByText('Studio lumineux à deux pas de la plage.').nth(1).waitFor()
  await shot(page, 'annonce')
  await page.reload()
  assert.equal(await page.getByLabel('Description').inputValue(), 'Studio lumineux à deux pas de la plage.')
  // Rédaction avec une IA : consigne tirée de la fiche, réponse collée, titre et description repris
  assert.match(first.prompt, /Consignes :/)
  assert.ok(!first.prompt.includes('€'))
  await page.getByRole('button', { name: 'Ouvrir' }).click()
  await page.getByLabel('Ce que vous aimez dans ce logement (facultatif)').fill('Vue sur le port')
  await page.getByLabel('Consigne pour l’IA').getByText(/Points forts indiqués par le propriétaire : Vue sur le port/).waitFor()
  await page.getByRole('link', { name: 'ChatGPT' }).waitFor()
  await page.getByLabel('Réponse de l’IA').fill('**Titre : Studio face au port de Sète**\n\nUn studio clair et calme, vue sur le port.')
  await page.getByRole('button', { name: 'Utiliser ce texte' }).click()
  await page.getByText('Texte repris dans votre annonce').waitFor()
  assert.equal(await page.getByLabel('Description').inputValue(), 'Un studio clair et calme, vue sur le port.')
  assert.equal(await page.getByLabel('Titre').inputValue(), 'Studio face au port de Sète')
  await shot(page, 'annonce-ia')
  const saved = await api(`/properties/${propertyId}/ad`, { token })
  assert.equal(saved.settings.title, 'Studio face au port de Sète')
  assert.equal(saved.settings.highlights, 'Vue sur le port')
  assert.match(saved.ad.text, /Un studio clair et calme[\s\S]*560 € par mois charges comprises/)
  await ctx.close()
  assert.deepEqual(errors, [])
})

test('candidature : formulaire public sans compte, choix du candidat, fiche locataire pré-remplie', async () => {
  const { token } = await newAccount()
  const { propertyId } = await completeLease(token)
  const { applyCode } = await api(`/properties/${propertyId}/apply-link`, { method: 'POST', token, body: { open: true } })
  assert.ok(applyCode)
  // Le candidat, sans compte
  const visitor = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const page = await visitor.newPage()
  const errors = []
  watch(page, errors)
  await page.goto(`${BASE}/candidature/${applyCode}`)
  await page.getByText('L’annonce').waitFor()
  await page.getByLabel('Prénom', { exact: true }).fill('Léa')
  await page.getByLabel('Nom', { exact: true }).fill('Martin')
  await page.getByLabel('Email').fill('lea.martin@example.fr')
  await page.getByLabel('Situation professionnelle').selectOption('EMPLOYEE')
  await page.getByLabel('Revenus nets du foyer, par mois').fill('2400')
  await page.getByRole('button', { name: 'Garantie Visale' }).click()
  await page.getByText('J’accepte que ces informations').click()
  await shot(page, 'candidature')
  await page.getByRole('button', { name: 'Envoyer ma candidature' }).click()
  await page.getByText('Candidature envoyée.').waitFor()
  // Pièces demandées : déposées juste après, sans compte
  await page.getByLabel('Pièce d’identité (vous)').setInputFiles({ name: 'cni.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF\n') })
  await page.getByText('Reçu').first().waitFor()
  await shot(page, 'candidature-pieces')
  await page.getByRole('button', { name: 'Terminer' }).click()
  await visitor.close()
  assert.deepEqual(errors, [])
  // Le propriétaire choisit
  const list = await api(`/properties/${propertyId}/candidates`, { token })
  assert.equal(list.candidates.length, 1)
  assert.equal(list.candidates[0].rentShare, 23)
  assert.equal(list.candidates[0].documents[0].category, 'identity')
  const ctx = await signedInContext(browser, token)
  const owner = await ctx.newPage()
  owner.on('dialog', (d) => d.accept())
  await owner.goto(`${BASE}/espace/logements/${propertyId}/candidats`)
  // Message à copier pour répondre sur Leboncoin, SeLoger…
  await owner.getByText('Répondre aux personnes intéressées').waitFor()
  assert.match(await owner.getByLabel('Message').inputValue(), new RegExp(`/candidature/${applyCode}`))
  await shot(owner, 'candidats-message')
  await owner.getByRole('button', { name: 'Choisir ce candidat' }).click()
  await owner.waitForURL('**/espace/baux/nouveau?**')
  const tenants = await api('/tenants', { token })
  const lea = tenants.find((t) => /Martin/.test(t.name) && /Léa/.test(t.name))
  assert.ok(lea, 'fiche locataire créée')
  const file = (await api(`/tenants/${lea.id}`, { token })).file
  assert.equal(file.email, 'lea.martin@example.fr')
  assert.equal(file.guarantee, 'VISALE')
  assert.deepEqual(file.documents.map((d) => [d.category, d.source]), [['identity', 'TENANT']])
  assert.equal((await api(`/properties/${propertyId}/candidates`, { token })).candidates.length, 0, 'candidature effacée')
  await ctx.close()
})

test('déclaration de revenus : loyers encaissés repris, intérêts d’emprunt gardés', async () => {
  const { token } = await newAccount()
  const vide = await completeLease(token, { furnished: false })
  await api(`/leases/${vide.leaseId}/sign`, { method: 'POST', token })
  const year = new Date().getFullYear()
  await api(`/leases/${vide.leaseId}/payments`, { method: 'POST', token, body: { period: `${year}-10` } })
  await api(`/properties/${vide.propertyId}/tax/${year}`, { method: 'PUT', token, body: { loanInterestCents: 120000 } })
  const tax = await api(`/money/tax?year=${year}`, { token })
  assert.equal(tax.empty.grossRentCents, 51000)
  const lines = Object.fromEntries(tax.properties[0].lines.map((l) => [l.line, l.cents]))
  assert.equal(lines['211'], 51000)
  assert.equal(lines['250'], 120000)
  assert.equal(tax.empty.better, 'REAL')
  const ctx = await signedInContext(browser, token)
  const page = await ctx.newPage()
  const errors = []
  watch(page, errors)
  await page.goto(`${BASE}/espace/argent`)
  await page.getByRole('link', { name: 'Déclaration de revenus' }).click()
  await page.getByRole('button', { name: String(year) }).click()
  await page.getByText('Case 4BE de la déclaration 2042').waitFor()
  await shot(page, 'declaration')
  await ctx.close()
  assert.deepEqual(errors, [])
})

test('bilan : résultat par logement, prix d’achat gardé et rendement brut', async () => {
  const { token } = await newAccount()
  const { leaseId, propertyId } = await completeLease(token, { furnished: false })
  await api(`/leases/${leaseId}/sign`, { method: 'POST', token })
  const year = new Date().getFullYear()
  await api(`/leases/${leaseId}/payments`, { method: 'POST', token, body: { period: `${year}-10` } })
  await api(`/properties/${propertyId}/purchase`, { method: 'PUT', token, body: { priceCents: 12_000_000 } })
  const r = await api(`/money/report?year=${year}`, { token })
  const mine = r.properties.find((p) => p.id === propertyId)
  assert.equal(mine.rentCents, 51000)
  assert.equal(mine.grossYield, 5.1)
  const ctx = await signedInContext(browser, token)
  const page = await ctx.newPage()
  const errors = []
  watch(page, errors)
  await page.goto(`${BASE}/espace/argent`)
  await page.getByRole('link', { name: 'Bilan', exact: true }).click()
  await page.getByText('Rendement brut : 5,1 % par an.').waitFor()
  await shot(page, 'bilan')
  await ctx.close()
  assert.deepEqual(errors, [])
})

test('intervention : artisan ajouté au carnet, dépense créée quand elle est terminée', async () => {
  const { token } = await newAccount()
  const { propertyId } = await completeLease(token)
  const i = await api(`/properties/${propertyId}/interventions`, { method: 'POST', token, body: { title: 'Fuite sous l’évier', status: 'PLANNED', date: new Date(Date.now() + 3 * 86_400_000).toISOString().slice(0, 10), newContact: { name: 'Plomberie Martin', trade: 'plombier', phone: '06 12 34 56 78' } } })
  const contacts = (await api('/contacts', { token })).filter((c) => c.kind === 'ARTISAN')
  assert.equal(contacts.length, 1)
  // Le syndic de la fiche du logement est aussi dans le carnet.
  assert.ok((await api('/contacts', { token })).some((c) => c.kind === 'SYNDIC'))
  assert.equal(contacts[0].name, 'Plomberie Martin')
  const today = await api('/today', { token })
  assert.ok(today.upcoming.some((u) => /Fuite sous l’évier avec Plomberie Martin/.test(u.label)))
  const done = await api(`/interventions/${i.id}`, { method: 'PUT', token, body: { title: i.title, status: 'DONE', date: new Date().toISOString().slice(0, 10), contactId: contacts[0].id, costCents: 18000, expenseCategory: 'REPAIR' } })
  assert.ok(done.expenseId)
  const money = await api(`/money?year=${new Date().getFullYear()}`, { token })
  assert.ok(money.expenses.some((e) => e.amountCents === 18000 && /Plomberie Martin/.test(e.vendor)))
  const ctx = await signedInContext(browser, token)
  const page = await ctx.newPage()
  const errors = []
  watch(page, errors)
  await page.goto(`${BASE}/espace/logements/${propertyId}`)
  await page.getByText('Fuite sous l’évier').first().waitFor()
  await page.goto(`${BASE}/espace/carnet`)
  await page.getByText('Plomberie Martin').first().waitFor()
  await shot(page, 'carnet')
  await ctx.close()
  assert.deepEqual(errors, [])
})

test('corbeille : une dépense supprimée se restaure à l’identique', async () => {
  const { token } = await newAccount()
  const { propertyId } = await completeLease(token)
  const date = new Date().toISOString().slice(0, 10)
  const e = await api('/expenses', { method: 'POST', token, body: { propertyId, vendor: 'Serrurerie Dupont', category: 'REPAIR', amountCents: 9500, date } })
  await api(`/expenses/${e.id}`, { method: 'DELETE', token })
  let money = await api(`/money?year=${new Date().getFullYear()}`, { token })
  assert.ok(!money.expenses.some((x) => x.vendor === 'Serrurerie Dupont'))
  const ctx = await signedInContext(browser, token)
  const page = await ctx.newPage()
  const errors = []
  watch(page, errors)
  await page.goto(`${BASE}/espace/corbeille`)
  await page.getByText(/Serrurerie Dupont/).first().waitFor()
  await shot(page, 'corbeille')
  await page.getByRole('button', { name: 'Restaurer' }).click()
  await page.getByText('La corbeille est vide.').waitFor()
  money = await api(`/money?year=${new Date().getFullYear()}`, { token })
  assert.ok(money.expenses.some((x) => x.vendor === 'Serrurerie Dupont' && x.amountCents === 9500))
  await ctx.close()
  assert.deepEqual(errors, [])
})

test('immeuble : les logements à la même adresse sont regroupés', async () => {
  const { token } = await newAccount()
  for (const label of ['T2 du 1er', 'Studio du 3e']) await api('/properties', { method: 'POST', token, body: { label, address: '8 rue des Lilas', postalCode: '69003', city: 'Lyon' } })
  await api('/properties', { method: 'POST', token, body: { label: 'Maison', address: '2 chemin Vert', postalCode: '69005', city: 'Lyon' } })
  const ctx = await signedInContext(browser, token)
  const page = await ctx.newPage()
  const errors = []
  watch(page, errors)
  await page.goto(`${BASE}/espace/logements`)
  await page.getByRole('heading', { name: '8 rue des Lilas' }).waitFor()
  await page.getByText('Même immeuble · 2 logements').waitFor()
  assert.equal(await page.getByRole('heading', { name: '2 chemin Vert' }).count(), 0)
  await shot(page, 'immeuble')
  await ctx.close()
  assert.deepEqual(errors, [])
})
