/**
 * Annexes officielles proposées avec le bail, reproduites à l'identique (seule la mise en page est propre à Bailio) :
 * - liste des réparations locatives, annexe du décret n° 87-712 du 26 août 1987 (LEGITEXT000006066148) ;
 * - liste des charges récupérables, annexe du décret n° 87-713 du 26 août 1987 (LEGITEXT000006066149).
 */
import type { NoticeBlock } from './notice-text.js'

export const REPAIRS_BLOCKS: NoticeBlock[] = [
  {"t": "h", "n": "I", "x": "Parties extérieures dont le locataire a l'usage exclusif", "lvl": 1},
  {"t": "sub", "x": "a) Jardins privatifs :"},
  {"t": "p", "x": "Entretien courant, notamment des allées, pelouses, massifs, bassins et piscines ; taille, élagage, échenillage des arbres et arbustes ;"},
  {"t": "p", "x": "Remplacement des arbustes ; réparation et remplacement des installations mobiles d'arrosage."},
  {"t": "sub", "x": "b) Auvents, terrasses et marquises :"},
  {"t": "p", "x": "Enlèvement de la mousse et des autres végétaux."},
  {"t": "sub", "x": "c) Descentes d'eaux pluviales, chéneaux et gouttières :"},
  {"t": "p", "x": "Dégorgement des conduits."},
  {"t": "h", "n": "II", "x": "Ouvertures intérieures et extérieures", "lvl": 1},
  {"t": "sub", "x": "a) Sections ouvrantes telles que portes et fenêtres :"},
  {"t": "p", "x": "Graissage des gonds, paumelles et charnières ;"},
  {"t": "p", "x": "Menues réparations des boutons et poignées de portes, des gonds, crémones et espagnolettes ; remplacement notamment de boulons, clavettes et targettes."},
  {"t": "sub", "x": "b) Vitrages :"},
  {"t": "p", "x": "Réfection des mastics ;"},
  {"t": "p", "x": "Remplacement des vitres détériorées."},
  {"t": "sub", "x": "c) Dispositifs d'occultation de la lumière tels que stores et jalousies :"},
  {"t": "p", "x": "Graissage ;"},
  {"t": "p", "x": "Remplacement notamment de cordes, poulies ou de quelques lames."},
  {"t": "sub", "x": "d) Serrures et verrous de sécurité :"},
  {"t": "p", "x": "Graissage ;"},
  {"t": "p", "x": "Remplacement de petites pièces ainsi que des clés égarées ou détériorées."},
  {"t": "sub", "x": "e) Grilles :"},
  {"t": "p", "x": "Nettoyage et graissage ;"},
  {"t": "p", "x": "Remplacement notamment de boulons, clavettes, targettes."},
  {"t": "h", "n": "III", "x": "Parties intérieures", "lvl": 1},
  {"t": "sub", "x": "a) Plafonds, murs intérieurs et cloisons :"},
  {"t": "p", "x": "Maintien en état de propreté ;"},
  {"t": "p", "x": "Menus raccords de peintures et tapisseries ; remise en place ou remplacement de quelques éléments des matériaux de revêtement tels que faïence, mosaïque, matière plastique ; rebouchage des trous rendu assimilable à une réparation par le nombre, la dimension et l'emplacement de ceux-ci."},
  {"t": "sub", "x": "b) Parquets, moquettes et autres revêtements de sol :"},
  {"t": "p", "x": "Encaustiquage et entretien courant de la vitrification ;"},
  {"t": "p", "x": "Remplacement de quelques lames de parquets et remise en état, pose de raccords de moquettes et autres revêtements de sol, notamment en cas de taches et de trous."},
  {"t": "sub", "x": "c) Placards et menuiseries telles que plinthes, baguettes et moulures :"},
  {"t": "p", "x": "Remplacement des tablettes et tasseaux de placard et réparation de leur dispositif de fermeture ; fixation de raccords et remplacement de pointes de menuiseries."},
  {"t": "h", "n": "IV", "x": "Installations de plomberie", "lvl": 1},
  {"t": "sub", "x": "a) Canalisations d'eau :"},
  {"t": "p", "x": "Dégorgement :"},
  {"t": "p", "x": "Remplacement notamment de joints et de colliers."},
  {"t": "sub", "x": "b) Canalisations de gaz :"},
  {"t": "p", "x": "Entretien courant des robinets, siphons et ouvertures d'aération ;"},
  {"t": "p", "x": "Remplacement périodique des tuyaux souples de raccordement."},
  {"t": "sub", "x": "c) Fosses septiques, puisards et fosses d'aisance :"},
  {"t": "p", "x": "Vidange."},
  {"t": "sub", "x": "d) Chauffage, production d'eau chaude et robinetterie :"},
  {"t": "p", "x": "Remplacement des bilames, pistons, membranes, boîtes à eau, allumage piézo-électrique, clapets et joints des appareils à gaz ;"},
  {"t": "p", "x": "Rinçage et nettoyage des corps de chauffe et tuyauteries ;"},
  {"t": "p", "x": "Remplacement des joints, clapets et presse-étoupes des robinets ;"},
  {"t": "p", "x": "Remplacement des joints, flotteurs et joints cloches des chasses d'eau."},
  {"t": "sub", "x": "e) Eviers et appareils sanitaires :"},
  {"t": "p", "x": "Nettoyage des dépôts de calcaire, remplacement des tuyaux flexibles de douches."},
  {"t": "h", "n": "V", "x": "Équipements d'installations d'électricité", "lvl": 1},
  {"t": "p", "x": "Remplacement des interrupteurs, prises de courant, coupe-circuits et fusibles, des ampoules, tubes lumineux ; réparation ou remplacement des baguettes ou gaines de protection."},
  {"t": "h", "n": "VI", "x": "Autres équipements mentionnés au contrat de location", "lvl": 1},
  {"t": "p", "x": "a) Entretien courant et menues réparations des appareils tels que réfrigérateurs, machines à laver le linge et la vaisselle, sèche-linge, hottes aspirantes, adoucisseurs, capteurs solaires, pompes à chaleur, appareils de conditionnement d'air, antennes individuelles de radiodiffusion et de télévision, meubles scellés, cheminées, glaces et miroirs ;"},
  {"t": "p", "x": "b) Menues réparations nécessitées par la dépose des bourrelets ;"},
  {"t": "p", "x": "c) Graissage et remplacement des joints des vidoirs ;"},
  {"t": "p", "x": "d) Ramonage des conduits d'évacuation des fumées et des gaz et conduits de ventilation."},
]

export const CHARGES_BLOCKS: NoticeBlock[] = [
  {"t": "h", "n": "I", "x": "Ascenseurs et monte-charge", "lvl": 1},
  {"t": "p", "x": "1. Dépenses d'électricité."},
  {"t": "sub", "x": "2. Dépenses d'exploitation, d'entretien courant, de menues réparations :"},
  {"t": "sub", "x": "a) Exploitation :"},
  {"t": "li", "x": "visite périodique, nettoyage et graissage des organes mécaniques ;"},
  {"t": "li", "x": "examen semestriel des câbles et vérification annuelle des parachutes ;"},
  {"t": "li", "x": "nettoyage annuel de la cuvette, du dessus de la cabine et de la machinerie ;"},
  {"t": "li", "x": "dépannage ne nécessitant pas de réparations ou fournitures de pièces ;"},
  {"t": "li", "x": "tenue d'un dossier par l'entreprise d'entretien mentionnant les visites techniques, incidents et faits importants touchant l'appareil."},
  {"t": "p", "x": "b) Fournitures relatives à des produits ou à du petit matériel d'entretien (chiffons, graisses et huiles nécessaires) et aux lampes d'éclairage de la cabine."},
  {"t": "sub", "x": "c) Menues réparations :"},
  {"t": "li", "x": "de la cabine (boutons d'envoi, paumelles de portes, contacts de portes, ferme-portes automatiques, coulisseaux de cabine, dispositif de sécurité de seuil et cellule photo-électrique) ;"},
  {"t": "li", "x": "des paliers (ferme-portes mécaniques, électriques ou pneumatiques, serrures électromécaniques, contacts de porte et boutons d'appel) ;"},
  {"t": "li", "x": "des balais du moteur et fusibles."},
  {"t": "h", "n": "II", "x": "Eau froide, eau chaude et chauffage collectif des locaux privatifs et des parties communes", "lvl": 1},
  {"t": "sub", "x": "1. Dépenses relatives :"},
  {"t": "li", "x": "à l'eau froide et chaude des locataires ou occupants du bâtiment ou de l'ensemble des bâtiments d'habitation concernés ;"},
  {"t": "li", "x": "à l'eau nécessaire à l'entretien courant des parties communes du ou desdits bâtiments, y compris la station d'épuration ;"},
  {"t": "li", "x": "à l'eau nécessaire à l'entretien courant des espaces extérieurs ;"},
  {"t": "li", "x": "aux produits nécessaires à l'exploitation, à l'entretien et au traitement de l'eau ;"},
  {"t": "li", "x": "à l'électricité ;"},
  {"t": "li", "x": "au combustible ou à la fourniture d'énergie, quelle que soit sa nature."},
  {"t": "p", "x": "Les dépenses relatives à la consommation d'eau incluent l'ensemble des taxes et redevances ainsi que les sommes dues au titre de la redevance d'assainissement, à l'exclusion de celles auxquelles le propriétaire est astreint en application de l'article L. 35-5 du code de la santé publique."},
  {"t": "sub", "x": "2. Dépenses d'exploitation, d'entretien courant et de menues réparations :"},
  {"t": "sub", "x": "a) Exploitation et entretien courant :"},
  {"t": "li", "x": "nettoyage des gicleurs, électrodes, filtres et clapets des brûleurs ;"},
  {"t": "li", "x": "entretien courant et graissage des pompes de relais, jauges, contrôleurs de niveau ainsi que des groupes moto-pompes et pompes de puisards ;"},
  {"t": "li", "x": "graissage des vannes et robinets et réfection des presse-étoupes ;"},
  {"t": "li", "x": "remplacement des ampoules des voyants lumineux et ampoules de chaufferie ;"},
  {"t": "li", "x": "entretien et réglage des appareils de régulation automatique et de leurs annexes ;"},
  {"t": "li", "x": "vérification et entretien des régulateurs de tirage ;"},
  {"t": "li", "x": "réglage des vannes, robinets et tés ne comprenant pas l'équilibrage ;"},
  {"t": "li", "x": "purge des points de chauffage ;"},
  {"t": "li", "x": "frais de contrôles de combustion ;"},
  {"t": "li", "x": "entretien des épurateurs de fumée ;"},
  {"t": "li", "x": "opérations de mise en repos en fin de saison de chauffage, rinçage des corps de chauffe et tuyauteries, nettoyage de chaufferies, y compris leurs puisards et siphons, ramonage des chaudières, carneaux et cheminées ;"},
  {"t": "li", "x": "conduite de chauffage ;"},
  {"t": "li", "x": "frais de location, d'entretien et de relevé des compteurs généraux et individuels ;"},
  {"t": "li", "x": "entretien de l'adoucisseur, du détartreur d'eau, du surpresseur et du détendeur ;"},
  {"t": "li", "x": "contrôles périodiques visant à éviter les fuites de fluide frigorigène des pompes à chaleur ;"},
  {"t": "li", "x": "vérification, nettoyage et graissage des organes des pompes à chaleur ;"},
  {"t": "li", "x": "nettoyage périodique de la face extérieure des capteurs solaires ;"},
  {"t": "li", "x": "vérification, nettoyage et graissage des organes des capteurs solaires."},
  {"t": "sub", "x": "b) Menues réparations dans les parties communes ou sur des éléments d'usage commun :"},
  {"t": "li", "x": "réparation de fuites sur raccords et joints ;"},
  {"t": "li", "x": "remplacement des joints, clapets et presse-étoupes ;"},
  {"t": "li", "x": "rodage des sièges de clapets ;"},
  {"t": "li", "x": "menues réparations visant à remédier aux fuites de fluide frigorigène des pompes à chaleur ;"},
  {"t": "li", "x": "recharge en fluide frigorigène des pompes à chaleur."},
  {"t": "h", "n": "III", "x": "Installations individuelles", "lvl": 1},
  {"t": "sub", "x": "Chauffage et production d'eau chaude, distribution d'eau dans les parties privatives :"},
  {"t": "p", "x": "1. Dépenses d'alimentation commune de combustible ;"},
  {"t": "sub", "x": "2. Exploitation et entretien courant, menues réparations :"},
  {"t": "sub", "x": "a) Exploitation et entretien courant :"},
  {"t": "li", "x": "réglage de débit et température de l'eau chaude sanitaire ;"},
  {"t": "li", "x": "vérification et réglage des appareils de commande, d'asservissement, de sécurité d'aquastat et de pompe ;"},
  {"t": "li", "x": "dépannage ;"},
  {"t": "li", "x": "contrôle des raccordements et de l'alimentation des chauffe-eau électriques, contrôle de l'intensité absorbée ;"},
  {"t": "li", "x": "vérification de l'état des résistances, des thermostats, nettoyage ;"},
  {"t": "li", "x": "réglage des thermostats et contrôle de la température d'eau ;"},
  {"t": "li", "x": "contrôle et réfection d'étanchéité des raccordements eau froide - eau chaude ;"},
  {"t": "li", "x": "contrôle des groupes de sécurité ;"},
  {"t": "li", "x": "rodage des sièges de clapets des robinets ;"},
  {"t": "li", "x": "réglage des mécanismes de chasses d'eau."},
  {"t": "sub", "x": "b) Menues réparations :"},
  {"t": "li", "x": "remplacement des bilames, pistons, membranes, boîtes à eau, allumage piézo-électrique, clapets et joints des appareils à gaz ;"},
  {"t": "li", "x": "rinçage et nettoyage des corps de chauffe et tuyauteries ;"},
  {"t": "li", "x": "remplacement des joints, clapets et presse-étoupes des robinets ;"},
  {"t": "li", "x": "remplacement des joints, flotteurs et joints cloches des chasses d'eau."},
  {"t": "h", "n": "IV", "x": "Parties communes intérieures au bâtiment ou à l'ensemble des bâtiments d'habitation", "lvl": 1},
  {"t": "sub", "x": "1. Dépenses relatives :"},
  {"t": "li", "x": "à l'électricité ;"},
  {"t": "li", "x": "aux fournitures consommables, notamment produits d'entretien, balais et petit matériel assimilé nécessaires à l'entretien de propreté, sel."},
  {"t": "sub", "x": "2. Exploitation et entretien courant, menues réparations :"},
  {"t": "p", "x": "a) Entretien de la minuterie, pose, dépose et entretien des tapis ;"},
  {"t": "p", "x": "b) Menues réparations des appareils d'entretien de propreté tels qu'aspirateur."},
  {"t": "p", "x": "3. Entretien de propreté (frais de personnel)."},
  {"t": "h", "n": "V", "x": "Espaces extérieurs au bâtiment ou à l'ensemble de bâtiments d'habitation (voies de circulation, aires de stationnement, abords et espaces verts, aires et équipements de jeux)", "lvl": 1},
  {"t": "sub", "x": "1. Dépenses relatives :"},
  {"t": "li", "x": "à l'électricité ;"},
  {"t": "li", "x": "à l'essence et l'huile ;"},
  {"t": "li", "x": "aux fournitures consommables utilisées dans l'entretien courant : ampoules ou tubes d'éclairage, engrais, produits bactéricides et insecticides, produits tels que graines, fleurs, plants, plantes de remplacement, à l'exclusion de celles utilisées pour la réfection de massifs, plates-bandes ou haies."},
  {"t": "p", "x": "2."},
  {"t": "sub", "x": "a) Exploitation et entretien courant : opérations de coupe, désherbage, sarclage, ratissage, nettoyage et arrosage concernant :"},
  {"t": "li", "x": "les allées, aires de stationnement et abords ;"},
  {"t": "li", "x": "les espaces verts (pelouses, massifs, arbustes, haies vives, plates-bandes) ;"},
  {"t": "li", "x": "les aires de jeux ;"},
  {"t": "li", "x": "les bassins, fontaines, caniveaux, canalisations d'évacuation des eaux pluviales ;"},
  {"t": "li", "x": "entretien du matériel horticole ;"},
  {"t": "li", "x": "remplacement du sable des bacs et du petit matériel de jeux."},
  {"t": "p", "x": "b) Peinture et menues réparations des bancs de jardins et des équipements de jeux et grillages."},
  {"t": "h", "n": "VI", "x": "Hygiène", "lvl": 1},
  {"t": "sub", "x": "1. Dépenses de fournitures consommables :"},
  {"t": "li", "x": "sacs en plastique et en papier nécessaires à l'élimination des rejets ;"},
  {"t": "li", "x": "produits relatifs à la désinsectisation et à la désinfection, y compris des colonnes sèches de vide-ordures."},
  {"t": "sub", "x": "2. Exploitation et entretien courant :"},
  {"t": "li", "x": "entretien et vidange des fosses d'aisances ;"},
  {"t": "li", "x": "entretien des appareils de conditionnement des ordures."},
  {"t": "p", "x": "3. Elimination des rejets (frais de personnel)."},
  {"t": "h", "n": "VII", "x": "Equipements divers du bâtiment ou de l'ensemble de bâtiments d'habitation", "lvl": 1},
  {"t": "p", "x": "1. La fourniture d'énergie nécessaire à la ventilation mécanique."},
  {"t": "sub", "x": "2. Exploitation et entretien courant :"},
  {"t": "li", "x": "ramonage des conduits de ventilation ;"},
  {"t": "li", "x": "entretien de la ventilation mécanique ;"},
  {"t": "li", "x": "entretien des dispositifs d'ouverture automatique ou codée et des interphones ;"},
  {"t": "li", "x": "visites périodiques à l'exception des contrôles réglementaires de sécurité, nettoyage et graissage de l'appareillage fixe de manutention des nacelles de nettoyage des façades vitrées."},
  {"t": "sub", "x": "3. Divers :"},
  {"t": "li", "x": "abonnement des postes de téléphone à la disposition des locataires."},
  {"t": "h", "n": "VIII", "x": "Impositions et redevances", "lvl": 1},
  {"t": "p", "x": "Droit de bail."},
  {"t": "p", "x": "Taxe ou redevance d'enlèvement des ordures ménagères."},
  {"t": "p", "x": "Taxe de balayage."},
]
