import type { ContractInput } from '../domain/contract.js'

/** Jeu de données d'exemple (maquette « Maison chemin des Vignes ») : aperçus et tests des documents. */
export const SAMPLE_CONTRACT: ContractInput = {
  landlord: { kind: 'PERSON', civility: 'MADAME', firstNames: 'Claire', lastName: 'Dubois', birthDate: '1978-06-02', birthPlace: 'Nîmes', address: "8 rue de l'Aiguillerie, 34000 Montpellier", email: 'claire.dubois@email.fr', agent: { enabled: false } },
  property: {
    label: 'Maison chemin des Vignes',
    address: '12 chemin des Vignes, 34120 Pézenas',
    habitat: 'INDIVIDUAL',
    legalRegime: 'MONO',
    furnished: false,
    destination: 'HABITATION',
    constructionPeriod: '1975_1989',
    surface: 88,
    rooms: 4,
    roomList: [{ name: 'Entrée' }, { name: 'Séjour' }, { name: 'Cuisine' }, { name: 'WC' }, { name: 'Chambre 1' }, { name: 'Chambre 2' }, { name: 'Chambre 3' }, { name: 'Salle de bain' }],
    heating: { mode: 'INDIVIDUAL', energy: 'GAS', appliance: 'Chaudière gaz murale' },
    hotWater: { mode: 'INDIVIDUAL' },
    equipments: ['kitchen', 'hob', 'oven', 'hood', 'bathtub', 'shutters', 'doubleGlazing', 'smokeDetector'],
    annexes: ['garage', 'garden', 'terrace', 'shed'],
    gardenArea: 400,
    tv: 'INDIVIDUAL',
    internet: 'FIBER',
    diagnostics: { dpe: { class: 'D', ges: 'C' }, erp: { date: '2026-09-01' }, electricity: { installOver15: true, date: '2024-03-02' }, gas: { hasGas: true, installOver15: true, date: '2024-03-02' } },
    market: { tense: false },
  },
  tenants: [{ civility: 'MADAME', firstNames: 'Sophie', lastName: 'Leroy', birthDate: '1996-02-14', birthPlace: 'Toulouse', email: 'sophie.leroy@email.fr', guarantee: 'CAUTION' }],
  guarantors: [{ civility: 'MONSIEUR', firstNames: 'Michel', lastName: 'Leroy', birthDate: '1965-11-03', birthPlace: 'Toulouse', link: 'père', address: '4 rue des Tanneurs, 31000 Toulouse', engagement: 'SOLIDAIRE', duration: 'FIXED', until: '2032-09-30', maxCents: 3900000, signMode: 'PAPER' }],
  terms: {
    kind: 'VIDE',
    startDate: '2026-10-01',
    rentCents: 93500,
    chargesCents: 4000,
    chargesMode: 'PROVISION',
    depositCents: 93500,
    paymentDay: 5,
    paymentTerm: 'ADVANCE',
    paymentMethod: 'TRANSFER',
    zone: { tense: false, control: false },
    previous: { rentedWithin18Months: true, lastRentCents: 91000, lastPaymentDate: '2026-08-05', lastRevisionDate: '2025-10-01' },
    revision: { enabled: true, date: '10-01', irlQuarter: '2026-Q2', irlValue: 148.37 },
    works: { sinceLast: 'Remplacement du chauffe-eau (890 €, mars 2026).' },
    clauses: { resolutoire: true, solidarite: false, custom: ['Le locataire entretient le jardin et la haie.'] },
    signature: { place: 'Montpellier', date: '2026-09-28', mode: 'PAPER' },
  },
  version: { number: 1, date: '28/09/2026' },
}
